version: '3'

volumes:
  elasticsearch-data:
    driver: local
  mariadb-data:
    driver: local

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: es01
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elastic
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - logger.level=WARN
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - backend

  logstash:
  # image: docker.elastic.co/logstash/logstash:8.1.3
    build: ./logstash
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/queries/:/usr/share/logstash/config/queries/
    ports:
      - "5001:5001"
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      - es01
    networks:
      - backend

  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb-data:/var/lib/mysql
     #- ./logstash/test.sql:/tmp/test.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=books
      - MYSQL_USER=dbadm
      - MYSQL_PASSWORD=1234567
      - TZ=Europe/Berlin
    ports:
      - "3306:3306"
    networks:
      - backend

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend

networks:
  backend:
